version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
    - npm install --silent --no-progress
    - sls --version
  pre_build:
    commands:
    - npm run lint
    - npm run test
  build:
    commands:
    - printenv | grep '^[a-z]' >> .env
    - mkdir -p target/$stage
    - sls --version
    - serverless package --package target/$stage --stage $stage -v
  post_build:
    commands:
    - rm -rf node_modules
artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh
  - package.json
